using System.Timers;
using Blazing.Mvvm.ComponentModel;
using clypse.core.Enums;
using clypse.core.Password;
using CommunityToolkit.Mvvm.Input;

namespace clypse.portal.Application.ViewModels;

/// <summary>
/// ViewModel for the password field component. Manages show/hide toggle, complexity analysis, and password generator.
/// </summary>
public partial class PasswordFieldViewModel : ViewModelBase, IDisposable
{
    private readonly IPasswordComplexityEstimatorService? passwordComplexityEstimator;

    private bool showPassword;
    private bool showPasswordGenerator;
    private PasswordComplexityEstimatorResults? passwordComplexityResults;
    private string? lastAnalyzedPassword;
    private string? value;
    private System.Timers.Timer? debounceTimer;

    /// <summary>
    /// Initializes a new instance of the <see cref="PasswordFieldViewModel"/> class.
    /// </summary>
    /// <param name="passwordComplexityEstimator">Optional service for estimating password complexity.</param>
    public PasswordFieldViewModel(IPasswordComplexityEstimatorService? passwordComplexityEstimator = null)
    {
        this.passwordComplexityEstimator = passwordComplexityEstimator;
    }

    /// <summary>Gets a value indicating whether the password is displayed in plain text.</summary>
    public bool ShowPassword { get => showPassword; private set => SetProperty(ref showPassword, value); }

    /// <summary>Gets a value indicating whether the password generator is shown.</summary>
    public bool ShowPasswordGenerator { get => showPasswordGenerator; private set => SetProperty(ref showPasswordGenerator, value); }

    /// <summary>Gets the password complexity results.</summary>
    public PasswordComplexityEstimatorResults? PasswordComplexityResults { get => passwordComplexityResults; private set => SetProperty(ref passwordComplexityResults, value); }

    /// <summary>Gets or sets the current password value.</summary>
    public string? Value
    {
        get => value;
        set
        {
            if (SetProperty(ref this.value, value))
            {
                OnPropertyChanged(nameof(ComplexityColorClass));
                OnPropertyChanged(nameof(ComplexityBackgroundColorClass));
                OnPropertyChanged(nameof(ComplexityText));
                OnPropertyChanged(nameof(ComplexityPercentage));
            }
        }
    }

    /// <summary>Gets or sets the callback invoked when the value changes.</summary>
    public Func<string?, Task>? ValueChangedCallback { get; set; }

    /// <summary>Gets or sets the callback invoked when a password is generated.</summary>
    public Func<string, Task>? PasswordGeneratedCallback { get; set; }

    /// <summary>Gets the CSS class for the complexity colour.</summary>
    public string ComplexityColorClass => GetComplexityColorClass();

    /// <summary>Gets the CSS class for the complexity progress bar background.</summary>
    public string ComplexityBackgroundColorClass => GetComplexityBackgroundColorClass();

    /// <summary>Gets the human-readable complexity label.</summary>
    public string ComplexityText => GetComplexityText();

    /// <summary>Gets the complexity percentage (0–100) for the progress bar.</summary>
    public int ComplexityPercentage => GetComplexityPercentage();

    /// <summary>Toggles password visibility.</summary>
    [RelayCommand]
    public void TogglePasswordVisibility() => ShowPassword = !ShowPassword;

    /// <summary>Shows the password generator.</summary>
    [RelayCommand]
    public void ShowGenerator()
    {
        ShowPasswordGenerator = true;
    }

    /// <summary>Handles a password being generated by the generator dialog.</summary>
    /// <param name="password">The generated password string.</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public async Task HandlePasswordGeneratedAsync(string password)
    {
        Value = password;
        if (ValueChangedCallback != null)
        {
            await ValueChangedCallback(Value);
        }

        await UpdatePasswordComplexityAsync();
        ShowPasswordGenerator = false;

        if (PasswordGeneratedCallback != null)
        {
            await PasswordGeneratedCallback(password);
        }
    }

    /// <summary>Hides the password generator without accepting a password.</summary>
    [RelayCommand]
    public void HideGenerator() => ShowPasswordGenerator = false;

    /// <summary>
    /// Called when the password input value changes (direct input; fires ValueChanged callback).
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    public async Task OnPasswordChangedAsync()
    {
        if (ValueChangedCallback != null)
        {
            await ValueChangedCallback(Value);
        }

        await UpdatePasswordComplexityAsync();
    }

    /// <summary>
    /// Handles raw password input events (debounced complexity update).
    /// </summary>
    /// <param name="newValue">The new password value from input.</param>
    public void OnPasswordInput(string? newValue)
    {
        Value = newValue;

        debounceTimer?.Stop();
        debounceTimer?.Dispose();

        debounceTimer = new System.Timers.Timer(500);
        debounceTimer.Elapsed += async (_, _) =>
        {
            debounceTimer?.Stop();
            await UpdatePasswordComplexityAsync();
        };
        debounceTimer.Start();
    }

    /// <inheritdoc/>
    public new void Dispose()
    {
        debounceTimer?.Stop();
        debounceTimer?.Dispose();
        base.Dispose();
    }

    private async Task UpdatePasswordComplexityAsync()
    {
        if (passwordComplexityEstimator == null)
        {
            return;
        }

        try
        {
            if (string.IsNullOrEmpty(Value))
            {
                PasswordComplexityResults = null;
                lastAnalyzedPassword = null;
                return;
            }

            if (Value != lastAnalyzedPassword)
            {
                PasswordComplexityResults = await passwordComplexityEstimator.EstimateAsync(Value, true, CancellationToken.None);
                lastAnalyzedPassword = Value;
                OnPropertyChanged(nameof(ComplexityColorClass));
                OnPropertyChanged(nameof(ComplexityBackgroundColorClass));
                OnPropertyChanged(nameof(ComplexityText));
                OnPropertyChanged(nameof(ComplexityPercentage));
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error estimating password complexity: {ex.Message}");
            PasswordComplexityResults = null;
            lastAnalyzedPassword = null;
        }
    }

    private string GetComplexityColorClass()
    {
        if (PasswordComplexityResults == null)
        {
            return "text-dark";
        }

        return PasswordComplexityResults.ComplexityEstimation switch
        {
            PasswordComplexityEstimation.VeryWeak => "text-danger",
            PasswordComplexityEstimation.Weak => "text-warning",
            PasswordComplexityEstimation.Medium => "text-warning",
            PasswordComplexityEstimation.Strong => "text-success",
            PasswordComplexityEstimation.VeryStrong => "text-primary",
            _ => "text-dark"
        };
    }

    private string GetComplexityBackgroundColorClass()
    {
        if (PasswordComplexityResults == null)
        {
            return "bg-dark";
        }

        return PasswordComplexityResults.ComplexityEstimation switch
        {
            PasswordComplexityEstimation.VeryWeak => "bg-danger",
            PasswordComplexityEstimation.Weak => "bg-warning",
            PasswordComplexityEstimation.Medium => "bg-warning",
            PasswordComplexityEstimation.Strong => "bg-success",
            PasswordComplexityEstimation.VeryStrong => "bg-primary",
            _ => "bg-dark"
        };
    }

    private string GetComplexityText()
    {
        if (PasswordComplexityResults == null)
        {
            return "Unknown";
        }

        return PasswordComplexityResults.ComplexityEstimation switch
        {
            PasswordComplexityEstimation.None => "None",
            PasswordComplexityEstimation.Unknown => "Unknown",
            PasswordComplexityEstimation.VeryWeak => "Very Weak",
            PasswordComplexityEstimation.Weak => "Weak",
            PasswordComplexityEstimation.Medium => "Medium",
            PasswordComplexityEstimation.Strong => "Strong",
            PasswordComplexityEstimation.VeryStrong => "Very Strong",
            _ => "Unknown"
        };
    }

    private int GetComplexityPercentage()
    {
        if (PasswordComplexityResults == null)
        {
            return 0;
        }

        return PasswordComplexityResults.ComplexityEstimation switch
        {
            PasswordComplexityEstimation.VeryWeak => 20,
            PasswordComplexityEstimation.Weak => 40,
            PasswordComplexityEstimation.Medium => 60,
            PasswordComplexityEstimation.Strong => 80,
            PasswordComplexityEstimation.VeryStrong => 100,
            _ => 0
        };
    }
}
