coverage:
  status:
    project:
      default:
        target: auto
        threshold: 85%
    patch:
      default:
        target: auto
        threshold: 85%

ignore:
  - "clypse.portal.setup/Properties/**"
