AWSTemplateFormatVersion: '2010-09-09'
Description: Clypse portal foundation (S3 website, data bucket, Cognito, IAM, CloudFront)

Parameters:
  ResourcePrefix:
    Type: String
    Description: Prefix used for all named resources (e.g., myenv)
  AwsRegion:
    Type: String
    Description: AWS region for the deployment
  CloudFrontAlias:
    Type: String
    Default: ''
    Description: Optional custom domain alias for CloudFront (leave blank for default domain)
  CertificateArn:
    Type: String
    Default: ''
    Description: Optional ACM certificate ARN in us-east-1 for the alias (required if alias is set)
  InitialUserEmail:
    Type: String
    Description: Email/username for the initial user
  InitialUserTempPassword:
    Type: String
    Description: Temporary password for the initial user (user must reset on first sign-in)
    NoEcho: true

Conditions:
  UseCustomDomain: !And [!Not [!Equals [!Ref CloudFrontAlias, '']], !Not [!Equals [!Ref CertificateArn, '']]]

Mappings:
  WebsiteFiles:
    Defaults:
      Index: index.html
      Error: index.html

Resources:
  PortalBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ResourcePrefix}.clypse.portal"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: !FindInMap [WebsiteFiles, Defaults, Index]
        ErrorDocument: !FindInMap [WebsiteFiles, Defaults, Error]
      Tags:
        - Key: clypse:setup-id
          Value: !Select [2, !Split ['/', !Ref AWS::StackId]]
        - Key: clypse:setup-version
          Value: 'template'

  PortalBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PortalBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${PortalBucket}/*"

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ResourcePrefix}.clypse.data"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins:
              - 'http://localhost:8080'
              - !Sub "https://${CloudFrontDistribution.DomainName}"
            AllowedHeaders: ['*']
            ExposedHeaders: []
            MaxAge: 3000
      Tags:
        - Key: clypse:setup-id
          Value: !Select [2, !Split ['/', !Ref AWS::StackId]]
        - Key: clypse:setup-version
          Value: 'template'

  DataPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ResourcePrefix}.clypse.data.policy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource: !Sub "arn:aws:s3:::${DataBucket}"
            Condition:
              StringLike:
                s3:prefix:
                  - '${cognito-identity.amazonaws.com:sub}/*'
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub "arn:aws:s3:::${DataBucket}/${cognito-identity.amazonaws.com:sub}/*"

  AuthPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ResourcePrefix}.clypse.auth.policy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cognito-identity:GetCredentialsForIdentity
            Resource: '*'

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ResourcePrefix}.clypse.user.pool"
      AutoVerifiedAttributes: [email]

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${ResourcePrefix}.clypse.identity.pool.client"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "${ResourcePrefix}.clypse.identity.pool"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  AuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ResourcePrefix}.clypse.auth.role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      ManagedPolicyArns:
        - !Ref DataPolicy
        - !Ref AuthPolicy

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthRole.Arn

  InitialUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref UserPool
      Username: !Ref InitialUserEmail
      DesiredDeliveryMediums: [EMAIL]
      ForceAliasCreation: false
      UserAttributes:
        - Name: email
          Value: !Ref InitialUserEmail
        - Name: email_verified
          Value: 'true'
      # Temporary password requires subsequent reset by the user
      ValidationData: []
    DependsOn: UserPoolClient

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !Select [2, !Split ['/', !GetAtt PortalBucket.WebsiteURL]]
            Id: PortalWebsiteOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: PortalWebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        ViewerCertificate: !If
          - UseCustomDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        Aliases: !If [UseCustomDomain, [!Ref CloudFrontAlias], []]

Outputs:
  PortalBucketName:
    Value: !Ref PortalBucket
  DataBucketName:
    Value: !Ref DataBucket
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  IdentityPoolId:
    Value: !Ref IdentityPool
  AuthRoleArn:
    Value: !GetAtt AuthRole.Arn
  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
